from .menu_base import dic as menu_base
from .menu_wrap import dic as menu_wrap
from .menu_transaction_wrap import dic as menu_transaction_wrap
from .no_records import dic as no_records
from .record_cell import dic as record_cell
from .times_layer import dic as times_layer
from .times_wrap import dic as times_wrap
from .delrec_button import dic as delrec_button
from .delmenu_ask_wrap import dic as delmenu_ask_wrap
